spring:
  profiles:
    group:
      "local": "localms,localdb,common"
---
spring:
  profiles:
    group:
      "dev": "devdb,common,devms"
---
spring:
  config:
    activate:
      on-profile: "localms"
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: "devms"
---
spring:
  config:
    activate:
      on-profile: "localdb"
  h2:
    console:
      enabled: true
      path: /h2/library
      settings:
        trace: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:library;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 1234
    platform: h2
    initialization-mode: always
    schema: classpath*:/schema.sql
    data: classpath*:/data.sql
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
    show-sql: false
    hibernate:
      ddl-auto: none

server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: "devdb"
  datasource:
    hikari:
      driver-class-name: "com.mysql.jdbc.Driver"
      jdbc-url: jdbc:mysql://${MYSQL_HOST}:3306/librarydb?createDatabaseIfNotExist=true
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    initialization-mode: always
    schema: classpath*:/schema.sql
    data: classpath*:/data.sql
    continue-on-error: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: "common"
  thymeleaf:
    prefix: "classpath:/templates/"
    check-template-location: true
    suffix=: ".html"
    mode: "HTML"
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

springfox:
  documentation:
    swagger:
      v2:
        path: "/swagger/docs/v2"
